aquasecurity/postee

README.md
cfg.yaml
src/alertmgr/alertmgr.go
src/alertmgr/jira.go
src/utils/utils.go
src/webhooksrv.go
src/webserver/webserver.go

Codebase has been updated with new code from Aqua repos.

Codebase update

---

.github/workflows/go.yml
.github/workflows/publish-ecr.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.travis.yml
.yamllint
README.md
cfg.yaml
kubernetes/pv.yaml
kubernetes/pvc.yaml
kubernetes/webhook.yaml

Github actions with yaml-lint, and publish to docker and ecr.
The publish and release action works with tag version, to test it follow this steps:
```
git tag v1.0.0
git push origin v1.0.0
```
Please create the followers secrets:
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- DOCKER_HUB_ACCESS_TOKEN
- DOCKER_HUB_USERNAME

feat: release and publish in docker, ecr with github actions

---

.github/workflows/release.yml

Fix calling the correct name in Makefile test

fix: release github action

---

.github/workflows/go.yml
README.md
cfg.yaml

Add a check spell action for spelling mistakes.

chore: gh-action check spell

---

kubernetes/README.md
kubernetes/pv.yaml
kubernetes/pvc.yaml
kubernetes/webhook.yaml

Update the image name with postee for the kubernetes deploy

chore: update image with the name postee and readme

---

README.md
cfg.yaml
deploy/kubernetes/README.md
deploy/kubernetes/webhook.yaml
deploy/rego/image.rego
deploy/rego/policy.rego
deploy/rego/vulnerability.rego

Update the kubernetes deploy to support rego files samples

feat: opa samples

---

Dockerfile
Makefile

Adding the makefile.
I could run the test with success in this new version

chore: makefile

---

README.md

Seems like slack UI was changed. Updating information based on #113

Update slack integration details

---

.github/workflows/binaries.yml
README.md

@jerbia @krol3 
I've added an action which builds and publishes a binary file for Ubuntu 18.04.
I tested this yaml for my fork. you can see the result [here](https://github.com/afdesk/postee/releases/tag/v.1.1.2).
Thanks for review!

[issue-121] Add publish a binary file for Ubuntu 18.04

---

.github/workflows/publish-chart.yml
deploy/kubernetes/README.md
deploy/kubernetes/postee-cm.yaml
deploy/kubernetes/postee.yaml
deploy/kubernetes/rego-cm.yaml

- Publish helm chart in https://github.com/aquasecurity/helm-charts/
- Simplify the installations steps of postee ` k create -f deploy/kubernetes`

feat: publish postee chart

---

.goreleaser.yml
deploy/kubernetes/postee.yaml

removing liveness

---

.github/workflows/publish-chart.yml
deploy/kubernetes/postee-cm.yaml
deploy/kubernetes/postee.yaml

Removing rego-config volume, older manifest from v1

fix: helm fix

---

.github/workflows/publish-chart.yml

fix: latest tag in publish-chart

---

formatting/eval.go
formatting/eval_test.go
rego-templates/vuls-html.rego
rego-templates/vuls-slack.rego

fix(template): fix aqua url issues

---

.github/workflows/release.yml
.goreleaser.yml
Makefile
deploy/kubernetes/postee-ui.yaml
ui/backend/go.mod
ui/backend/go.sum

- Building the dockerfile.ui using goreleaser.
- Testing locally using ` goreleaser release --snapshot --rm-dist`

chore: goreleaser docker.ui

---

ui/frontend/package.json

Fix: fixed docker image postee-ui building

---

README.md
dbservice/dbparam.go
dbservice/dbparam_test.go
main.go

feat: added PATH_TO_DB environment variable

---

README.md

- fixing link
- http port in the readme

chore: fixing link and port in the readme

---

.github/workflows/publish-chart.yml
deploy/kubernetes/postee.yaml

Adding readiness and liveness to the k8s manifest in the postee-ui
After this PR https://github.com/aquasecurity/postee/pull/195

chore: adding readiness in k8s postee-ui

---

deploy/kubernetes/postee.yaml

k8s manifest adding filters volume

chore: k8s manifest filters volume

---

rego-templates/vuls-html.rego

fix(rego-html): support optional vulnerability summary

---

outputs/splunk.go

Fixed json unmarshal error for splunk
- Closes #239

fix(splunk): fixed json unmarshal

---

Dockerfile
Dockerfile.ui
ui/backend/go.mod

Fixes: https://github.com/aquasecurity/postee/issues/265

chore: Update Go version for dockerfile and ui/go.mod

---

cfg-actions.yaml
outputs/exec.go
outputs/exec_test.go
router/builders.go
router/initoutputs_test.go
router/integrations.go
router/router.go

feat(actions): Add the ability to specify inline exec scripts.

---

cfg-actions.yaml
outputs/exec.go
outputs/exec_test.go
outputs/http.go
outputs/http_test.go
router/builders.go
router/initoutputs_test.go
router/integrations.go

This PR adds:
fix(actions): Use request.Headers.Add() to set headers.
feat(action): Adds the ability to inline HTTP request body.

feat(actions): Improve HTTP Action

---

Dockerfile
deploy/kubernetes/postee-actions.yaml

feat(actions): Add Postee Actions for k8s config yaml.

---

cfg-docker-actions.yaml
docs/actions/actions.md
outputs/docker.go
outputs/docker_test.go
router/builders.go
router/integrations.go

This PR adds the following:
feat(actions): Add network name option for Docker action.
feat(actions): Add rego parsing within inputs.

feat(actions): Improve Docker Action

---

.github/workflows/publish-chart.yml
.gitignore
deploy/helm/postee/templates/postee-svc.yaml
deploy/helm/postee/templates/postee-ui-svc.yaml
deploy/helm/postee/templates/postee-ui.yaml
deploy/helm/postee/templates/postee.yaml

Fixes: #348 
- Fix missing files ignored by the .gitignore
It was tested in a EKS and kind cluster.

fix: missing files in helm chart

---

.github/workflows/publish-chart.yml

Fixes: https://github.com/actions-ecosystem/action-get-latest-tag/pull/19

fix(deps): Update latest tag action.

---

README.md

docs(routes): Document `serialize-actions`.

---

.github/workflows/aqua-cloud.yml
.github/workflows/go.yml
.github/workflows/publish-chart.yml
.github/workflows/publish-docs.yml
.github/workflows/release.yml
Makefile
config/cfg-actions.yaml

chore(actions): Improve Actions

---

ui/backend/uiserver/events.go
ui/backend/uiserver/events_test.go
ui/frontend/package-lock.json
ui/frontend/package.json
ui/frontend/yarn.lock

Also fixes a potential panic when /events might not be ready.

fix(events): Improve error messages.

---

deploy/helm/postee/Chart.yaml
deploy/helm/postee/values.yaml

This will enable the /events endpoint to be used out of the box with Tracee.

feat(helm): Upgrade helm chart values

---

actions/message.go
actions/message_test.go

feat(test): Improve test coverage and refactor

---

data/integrations.go
msgservice/msghandling.go
msgservice/msgservice_mocks_test.go
outputs/email.go
outputs/exec.go
outputs/http.go
outputs/jira.go
outputs/plugin.go
outputs/servicenow.go
outputs/slack.go
outputs/splunk.go
outputs/stdout.go
outputs/teams.go
outputs/webhook.go
router/api.go
router/loads_test.go
router/router.go
servicenow/insert_table.go
servicenow/servicenow_base.go

1) Returning a struct instead of string
2) Adding url to ticket to jira response
SLK-54336

Postee | Jira extra info

---

Dockerfile
Dockerfile.release
Makefile
docker-compose.yml

add config samples in the image postee release

chore: add config samples in the image postee release

---

ui/frontend/package-lock.json
ui/frontend/package.json
ui/frontend/src/App.vue
ui/frontend/src/components/EventDetails.vue
ui/frontend/src/components/RouteDetails.vue
ui/frontend/src/components/Routes.vue
ui/frontend/src/main.js
ui/frontend/yarn.lock

feat(ui): Add a introduction tour

---

ui/frontend/src/components/Actions.vue
ui/frontend/src/components/EventDetails.vue
ui/frontend/src/components/Routes.vue
ui/frontend/src/components/Settings.vue
ui/frontend/src/components/Templates.vue

Added help text for all pages of the UI.

feat(ui): Improved Messaging for UI elements.

---

README.md
router/api.go

Test Output - Support custom template

---

deploy/helm/postee/Chart.yaml
deploy/helm/postee/values.yaml

feat(helm): Bump up helm chart version.

---

rego-templates/trivy-jira.rego

Contributed by matt schuman on Aqua #postee Slack.

feat(rego): Add Trivy template for JIRA.

---

go.mod
outputs/customsmtp/auth.go
outputs/customsmtp/smtp.go
outputs/email.go
outputs/email_test.go

add support for email LOGIN auth mechanism.

replace smtp not supported standard lib with custom one.

---

rego-templates/incident-jira.rego
rego-templates/incident-slack.rego
rego-templates/insight-html.rego
rego-templates/insight-jira.rego
rego-templates/insight-slack.rego
rego-templates/vuls-html.rego
rego-templates/vuls-jira.rego
rego-templates/vuls-slack.rego

Postee templates - print application scope if exists

---

msgservice/msghandling.go

Extract route application scopes

---

ui/frontend/package-lock.json
ui/frontend/yarn.lock

run `npm audit fix --force` to fix `CVE-2022-37601 `

fix(ui): fix CVE-2022-37601 

---

regoservice/regocheck.go
regoservice/regocheck_test.go

Routes - support OR condition in route input

---

outputs/splunk.go

Splunk skips client verification for the server's certificate chain and host name, in order to support self-signed certs

splunk client skip tls verify

---

msgservice/msghandling.go
rego-templates/insight-html.rego
rego-templates/insight-jira.rego
rego-templates/insight-slack.rego
webserver/webserver.go

- fix application scope enrichments to support incidents.

---

deploy/helm/postee/templates/cfg-secret.yaml
deploy/helm/postee/templates/postee.yaml
deploy/helm/postee/values.yaml

- closes #552 
- remove both checksum and secret if existing secret has been enabled

config - allow for existing secret

---

actions/example/exec/defectdojo-curl-upload-scan.sh
config/cfg-trivy-operator-defectdojo.yaml
docs/actions.md
rego-templates/example/defectdojo/trivy-operator-defectdojo.rego
rego-templates/example/defectdojo/trivy-operator-defectdojo_test.rego

- REGO template + test case
- example Postee configuration
- inject TOKEN and URL using environment variable
- example shell script sending multipart/form-data POST request using CURL

DefectDojo - provide example for sending trivy reports using EXEC action

---

deploy/helm/postee/templates/postee.yaml
deploy/helm/postee/values.yaml

- credits to @fbuchmaier-abi for his work
- posted as PR because of CLA issues for @fbuchmaier-abi
- closes #506

helm - support for additional volumes

---

go.mod
go.sum

Cherry-pick of https://github.com/aquasecurity/postee/pull/569/commits/bbeb68e71a0b109f1cc958a9d667da212a64b7db

bump go-jira

---

rego-templates/incident-jira.rego
rego-templates/incident-servicenow.rego
rego-templates/incident-slack.rego
rego-templates/vuls-html.rego
rego-templates/vuls-jira.rego
rego-templates/vuls-servicenow.rego
rego-templates/vuls-slack.rego

This commit adds url links (received from the input) to all on premise related templates
Resolves-59360

Response Policy | Templates | Add direct link - On premise

---

docs/deployment.md

- closes #499 
- just convert the solution provided as recommendation to other users, tested on EKS running K8s version 1.23

docs/deployment - provide example for solving PVC attach issue

---

rego-templates/incident-jira.rego
rego-templates/incident-servicenow.rego
rego-templates/incident-slack.rego
rego-templates/vuls-html.rego
rego-templates/vuls-jira.rego
rego-templates/vuls-servicenow.rego
rego-templates/vuls-slack.rego

This reverts commit 16fb899d63d3eaff28d5c05fdfd7e415d78d22dc.

Revert "Response Policy | Templates | Add direct link - On premise"

---

rego-templates/issues-jira.rego

add table template for jira ticket

---

rego-templates/embedded.go
router/api.go
router/router.go
router/v2.go

Feat(): add option to init the router with a specific template (prevent all templates from being loaded)

feat(): init on specific template

---

cfg.yaml
deploy/helm/postee/values.yaml
deploy/kubernetes/postee.yaml
rego-templates/trivy-operator-jira.rego

copied the existing jira template and made it suitable for the trivy operator
and fixed the colomns and added summary with totals 
https://github.com/aquasecurity/postee/issues/598

add trivy operator template for jira

---

README.md

ref: https://github.com/aquasecurity/postee/issues/605#issuecomment-1699973268
Add to README.md how to release new versions of Postee.

docs: add flow to release new version

---

cfg.yaml
data/integrations.go
outputs/email.go
router/builders.go

Porting a fix from main postee:
https://github.com/aquasecurity/postee/pull/607
Resoves: SLK-69788

Integration | Email | SMTP HELO check rejects "localhost"

---

rego-templates/vuls-html.rego
rego-templates/vuls-jira.rego
rego-templates/vuls-slack.rego

This commit fixes the templates to pass the tests
Resolves: SLK-71876

Postee | Templates | Import if keyword

---

.github/workflows/go.yml
.github/workflows/publish-chart.yml
.github/workflows/release.yml
go.mod

also golangci-lint is updated for support Go 1.21

bumps up Go to 1.21.

---

data/integrations.go
rego-templates/incident-jira-fr.rego
router/builders.go

Add Language field to `OutputSettings` and french incident jira template.

add french incident jira integration
