Dockerfile

Alpine version is using go version [1.16.](https://hub.docker.com/layers/golang/library/golang/alpine/images/sha256-353e19718d4aa37cb38cf362e5aba23e22b8680bfc18255408ccd9b7b777c469?context=explore)
Fixing the dockerfile with the 1.15 to avoid errors with the `make all` 
```
#17 8.602 building....
#17 8.602 go install  webhooksrv
#17 8.606 go install: version is required when current directory is not in a module
#17 8.606 	Try 'go install webhooksrv@latest' to install the latest version
```
Testing the publish gh-action in the branch [docker-test](https://github.com/aquasecurity/postee/runs/2008941641?check_suite_focus=true)

chore: dockerfile alpine fix go version

---

ui/backend/go.mod
ui/backend/go.sum

Building the postee-ui I had this error
```
go: github.com/aquasecurity/postee@v1.1.1 requires
github.com/andygrunwald/go-jira@v1.14.0: missing go.sum entry; to add it:
go mod download github.com/andygrunwald/go-jira
The command '/bin/sh -c go build -o posteeui' returned a non-zero code: 1
```

chore: postee-ui mod jira 1.14

---

ui/backend/go.mod
ui/frontend/package.json
ui/frontend/yarn.lock

- automatic dependency update.
- replace vulnerable `node-forge` package from `v0.10.0` to `v1.0.0`.
- replace vulnerable `golang.org/x/crypto` package from `v0.0.0-20200622213623-75b288015ac9` to `v0.0.0-20201216223049-8b5274cf687f`.

chore(deps): update node and go dependencies

---

dbservice/boltdb/boltdb.go
dbservice/dbservice.go
dbservice/postgresdb/actions.go
dbservice/postgresdb/cfgcachesource.go
dbservice/postgresdb/checker.go
dbservice/postgresdb/close.go
dbservice/postgresdb/connect.go
dbservice/postgresdb/connect_test.go
dbservice/postgresdb/dbaggregator.go
dbservice/postgresdb/init.go
dbservice/postgresdb/plgstats.go
dbservice/postgresdb/sharedcfg.go
router/api_test.go
router/inittemplate_test.go
router/loads_test.go

This commit includes one change and one addition:
1. Reuse the Postgres DB connection instead of closing and opening for each operation.
2. Connecting to a Postgres server with retry functionality.

Reuse postgres db conncetion instance

---

msgservice/applicationscopeowner_test.go
msgservice/getuniqueid_test.go
msgservice/msghandling.go
msgservice/msgservice_test.go
msgservice/regocriteria_test.go
router/loads_test.go
router/routehandling_test.go
router/router.go

This commit contains code that moves the rego evaluation code to the
route handling process.
At its current implementation, the output handler checks for rego match - this
check is redundant since the output does not effect the matching process.

Evaluate rego rule once for every route (#257)

---

outputs/email.go
outputs/email_test.go

Fixes a case where user/pass are not specified for a vanilla SMTP email send #241 
Adds a variety of test cases via EmailSender interface.

feat: Handle SMTP auth better

---

deploy/kubernetes/postee.yaml

Fix issues related to k8s manifest in poste-ui https://github.com/aquasecurity/postee/issues/273

fix: k8s security context permissions

---

ui/backend/dbservice/getplgnstats.go
ui/backend/go.mod
ui/backend/go.sum
ui/backend/uiserver/config.go
ui/backend/uiserver/testplg.go

As described in #264. PosteeUI is still depending on an old Postee Versions and a build won't work anymore. 
This will require postee/v2 2.0.7

make PosteeUI depend on  postee v2 #264

---

cfg-actions.yaml
outputs/exec.go
outputs/exec_test.go
outputs/http.go
outputs/http_test.go
router/builders.go
router/goldens/test.txt
router/initoutputs_test.go
router/integrations.go
router/router.go

This PR introduces Postee Actions, a lightweight (no-code) workflows that allows users to configure Postee to execute ad-hoc but useful post processing steps.
Some use cases include (but are not limited):
1. As a security practitioner, I want to remove a vulnerable image from my node when Trivy scan detects a vulnerability in an image, so that I can keep vulnerable images unavailable for deployment.
2. As a security practitioner, I want to ship Tracee security notifications logs from my node when security events are detected, so that I can build a timelog for forensics purposes.
3. [WIP] As a Kubernetes operator, I want to add labels to my Kubernetes cluster when Starboard detects a vulnerable image in my cluster, so that I can effectively manage vulnerable deployments.
These are some …

feat: Introduce Postee Actions

---

.github/workflows/go.yml
README.md

Recently Codecov has had several availability issues which prevent us from merging PRs on time as the checks get stuck with no recourse to trigger them.

chore: Remove codecov

---

.goreleaser.yml

The official Starboard images are labeled following [the org.label-schema Label Schema](https://label-schema.org/). That schema has been deprecated in favor of [the superseeding OCI image spec annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md#back-compatibility-with-label-schema).

feat: using oci image spec annotations

---

cfg-k8s-actions.yaml
go.mod
go.sum
outputs/kubernetes.go
outputs/kubernetes_test.go
regoservice/eval.go

This PR adds the support for the following:
```
- name: my-k8s
type: kubernetes
enable: true
kube-namespace: "default"                         # Required. Kubernetes namespace to use.
kube-config-file: "/path/to/kubeconfig"           # Required. Path to .kubeconfig file
kube-label-selector: "app=nginx-app"              # Required, if specifying labels or annotations.
kube-actions:
labels:
foo-label: "bar-value"                        # Required. Label to add.
bar-label: event.input.SigMetadata.ID         # Optional. It is also possible to add labels based on event inputs.
annotations:
foo-annotation: "bar-value"
bar-annotation: event.input.SigMetadata.ID
```

feat(actions): Support Rego in Kubernetes Action input

---

.github/workflows/publish-chart.yml

Since we have postee-actions.yaml now within the deploy directory, we should be specific about the YAML we use to create.
Fixes:

fix(github): Use full path to k8s yaml.

---

.github/workflows/publish-chart.yml

- Removing the publish helm chart when pushed to the main branch.
- publish the helm chart only with the release tag 
- @simar7 we are using the same app version to the chart app, we use the latest tag publish. https://github.com/aquasecurity/postee/blob/main/.github/workflows/publish-chart.yml#L77

chore: gh publish helm manually using the release

---

.goreleaser.yml
deploy/helm/postee/values.yaml

Currently the helm chart is using the latest tag. This PR will fix it and use the latest image release postee `docker pull aquasec/postee:0.24.0`
```
k -n postee get statefulsets.apps -o wide
NAME         READY   AGE   CONTAINERS   IMAGES
app-postee   1/1     23m   postee       aquasec/postee:latest
k -n postee get deployments.apps -o wide
NAME           READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                     SELECTOR
app-posteeui   1/1     1            1           23m   postee       aquasec/postee-ui:latest   app.kubernetes.io/instance=app,app.kubernetes.io/name=postee-ui
```

chore: use the image tag of the release in the helm chart

---

docs/actions.md

Create the PR for this issue:-
Add information about optional/required fields in Actions documentation #380

Required Column added

---

rego-templates/trivy-vulns-slack.rego
rego-templates/trivy-vuls-slack-aggregation.rego

A template for slack to support trivy output.
Here the result 
Thanks @AndreyLevchenko

feat: trivy template for slack

---

actions/splunk.go
cfg.yaml
deploy/helm/postee/values.yaml
router/builders.go

Add skip tls verification for `Splunk`.
Use `tls-verify` for this.
- #496

feat(splunk): add skip tls verification

---

deploy/helm/postee/templates/cfg-configmap.yaml
deploy/helm/postee/templates/cfg-secret.yaml
deploy/helm/postee/templates/postee.yaml

Related to #479
A little bit of a lazy implementation but this way we could simply overwrite the whole content of the config file as a secret provided from another source (Hashicorp Vault + External Secrets Operator in our case)
Open for feedback of course but I am going to be on vacation for two weeks now.
Cheers!

feat(Helm): Provide sensitive values as secret

---

deploy/helm/postee/templates/postee.yaml
deploy/helm/postee/values.yaml
docs/advanced.md

This changes enables kubernetes secrets to be used as source for environment variables.
Environment variables can be used in the config file, as documented [here](https://aquasecurity.github.io/postee/advanced/#using-environment-variables-in-postee-configuration-file). However it was not possible to set this up with the helm chart.
With this change it is possible to define any secrets to be mounted into the container:
```
envFrom:
- my-env-secret-1
- my-env-secret-2
- ...
```

Feat(helm): environment variables from secret

---

rego-templates/common/common.rego
rego-templates/iac-html.rego
rego-templates/iac-jira.rego
rego-templates/iac-servicenow.rego
rego-templates/iac-slack.rego

- add `is_new` field in CVE tables:
- add `(x new)` in summary tables.

feat: add is_new field iac templates

---

Dockerfile.ui

Postee UI contains a dependency that wasn't updated yet and doesn't support the latest Node version (19).
I've changed the image for Node builder to Node 18.
Node 18 has Long Term Support (maintenance end is 2025-04-30), so I think it's ok.
- close #536

fix: update the image for Node builder

---

docs/examples/swit.yaml
docs/swit-integration.md
rego-templates/swit-json.rego
rego-templates/swit-text.rego

`swit-text` is based on the html-rego template. It's a bit dirty yet, but it should be expanded later. 
SWIT's API for text is really limited now.
`swit-json` is a simple json forwarding to SWIT.
a sample of `cgf.yaml`:
```yaml
name: tenant
aqua-server:
max-db-size: 1000MB
db-verify-interval: 1   
routes:
- name: stdout-swit
outputs: [ my-swit ]
template: swit-text
templates:
- name: swit-text
rego-package: postee.swit.text
outputs:
- name: my-swit
type: webhook
enable: true
url: https://hook.swit.io/chat/<>/<>
``

feat: add templates for swit integration to the enterprise branch

---

Dockerfile
Dockerfile.ui

- closes #553 
- buildx bake is setting two environment variables that we have to forward into the Dockerfile to prepare for multi architecture builds
- prepares for #541

Dockerfile - prepare for multi-architecture builds

---

docs/advanced.md

- improve readability
- first occasion is a variable name and thus it should be highlighted as code (as done for variable `input`)

docs/advanced - mark variable name as code

---

actions/jira_test.go
go.mod
go.sum

Jira 9.x had breaking changes - Atlassian removed [createmeta REST endpoint](https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html). so we updated [aquasecurity/go-jira](https://github.com/aquasecurity/go-jira).
before:
```sh
2023/06/06 12:31:37 Error while sending event: Failed to create meta project: failed to get create meta : request failed. Please analyze the request body for more details. Status code: 404
```
after:
```sh
2023/06/06 12:31:38 Created new jira issue 10000
```

fix: creating issues in Jira 9.x.x

---

Dockerfile.ui

Postee UI contains a dependency that does not support node 20.
I have downgraded the Node image version to 18. This is the LTS version that will be supported until April 2025
Closes #564

fix: downgrade the Node.js image from 20 to 18

---

go.mod
go.sum

This pull request addresses a particular issue encountered when using the Jira Cloud API's serverInfo endpoint. Currently, in certain cases, the serverInfo response contains a version that appears to be peculiar or unconventional. As a result, this pull request proposes an important fix to prevent the usage of API 9 for Jira Cloud.

fix: support Jira Cloud API

---

Dockerfile.release

Resolves #548 - adds curl and jq to the release image.
The apk command is changed to download the index only one time. Afterwards the cache is cleared.

feat: Add curl and jq to release image

---

deploy/helm/postee/Chart.yaml
deploy/helm/postee/values.yaml

Helm uses old version of Postee. 
Update it.

fix(helm): update postee version

---

actions/dependencytrack.go
actions/dependencytrack_test.go
cfg.yaml
deploy/helm/postee/values.yaml
docs/actions.md
go.mod
go.sum
rego-templates/trivy-operator-dependency-track.rego
router/builders.go
router/initoutputs_test.go
router/integrations.go
router/router.go
ui/frontend/src/components/ActionDetails.vue

ref https://github.com/aquasecurity/postee/issues/575
SBOM Report has been supported since Trivy Operator [0.15.0](https://github.com/aquasecurity/trivy-operator/releases/tag/v0.15.0) .
I want to execute a webhook to Dependency Track via Postee. (ref: https://github.com/aquasecurity/trivy-operator/issues/143#issuecomment-1582164314 )
In this Pull Request, I implemented the following:
- Added Integration of Dependency Track
- Added Template for sending Trivy Operator sbomReport to Dependency Track
Dependency Track uploads the BOM with ProjectName and ProjectVersion as keys.
Dependency Track Integration has the following specification:
- `ProjectName:ProjectVersion` is the template `title` .  (e.g. `busybox:latest`)
- BOM data is in the template `description` .
In this Pull Request, only …

feat: add dependency track integration

---

rego-templates/trivy-operator-slack.rego

copied trivy-vulns-slack.rego to trivy-operator-slack.rego and made it usable for the trivy operator output
improved it so the output now also includes the cve ids as url links to the primary url
https://github.com/aquasecurity/postee/issues/469

improve trivy operator slack template

---

deploy/helm/postee/values.yaml

Ref: https://github.com/aquasecurity/postee/issues/605
Currently, the image tag in values.yaml is used instead of `.Chart.AppVersion`. This means that the tag must be incremented each time it is released.
In this pull request, remove the tag specification in values.yaml and use the default `.Chart.AppVersion`.
https://github.com/aquasecurity/postee/blob/698003ebe7b0ded95b07f010b5fee5942b91eeee/deploy/helm/postee/templates/postee.yaml#L85
https://github.com/aquasecurity/postee/blob/698003ebe7b0ded95b07f010b5fee5942b91eeee/deploy/helm/postee/templates/postee-ui.yaml#L43
The tag in values.yaml is commented out for documentation.
```shell
$ helm template deploy/helm/postee | grep 'image: "aquasec/postee' -A4 -B4
containers:
- name: postee
securityContext:
{}
image: …
```

chore: image tag uses the default `.Chart.AppVersion`

---

rego-templates/incident-servicenow.rego
rego-templates/vuls-html.rego
rego-templates/vuls-servicenow.rego

Some rego templates were defined with a link to "url" like so:
`<a href="url">`
but the url is not a variable, so the links would send customers to "url", instead of the real URL.
To fix the issue, the href value is changed to:
`<a href="%s">`
and the %s is populated with the real URL.

Bug fix | Rego templates with a link to Aqua navigate to "url" instead of the real URL
